#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : oslo.privsep
Version  : 1.30.1
Release  : 3
URL      : https://files.pythonhosted.org/packages/a1/1b/3b269f4de8e4f88cd7334e389c6b8f19b8d07bfbf731da100e9f38d8b79e/oslo.privsep-1.30.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/a1/1b/3b269f4de8e4f88cd7334e389c6b8f19b8d07bfbf731da100e9f38d8b79e/oslo.privsep-1.30.1.tar.gz
Summary  : OpenStack library for privilege separation
Group    : Development/Tools
License  : Apache-2.0
Requires: oslo.privsep-bin
Requires: oslo.privsep-python3
Requires: oslo.privsep-license
Requires: oslo.privsep-python
Requires: cffi
Requires: enum34
Requires: eventlet
Requires: greenlet
Requires: msgpack
Requires: oslo.config
Requires: oslo.i18n
Requires: oslo.log
Requires: oslo.utils
BuildRequires : buildreq-distutils3
BuildRequires : hacking
BuildRequires : oslo.config
BuildRequires : oslo.log
BuildRequires : oslo.utils
BuildRequires : pbr
BuildRequires : python-dateutil

%description
Team and repository tags
        ========================

%package bin
Summary: bin components for the oslo.privsep package.
Group: Binaries
Requires: oslo.privsep-license = %{version}-%{release}

%description bin
bin components for the oslo.privsep package.


%package license
Summary: license components for the oslo.privsep package.
Group: Default

%description license
license components for the oslo.privsep package.


%package python
Summary: python components for the oslo.privsep package.
Group: Default
Requires: oslo.privsep-python3 = %{version}-%{release}

%description python
python components for the oslo.privsep package.


%package python3
Summary: python3 components for the oslo.privsep package.
Group: Default
Requires: python3-core

%description python3
python3 components for the oslo.privsep package.


%prep
%setup -q -n oslo.privsep-1.30.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1538059006
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/oslo.privsep
cp LICENSE %{buildroot}/usr/share/doc/oslo.privsep/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/privsep-helper

%files license
%defattr(0644,root,root,0755)
/usr/share/doc/oslo.privsep/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
