#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : oslo.privsep
Version  : 2.2.1
Release  : 28
URL      : https://files.pythonhosted.org/packages/55/76/a9d5657970658a884d452c98d7360a7e313fd218ccb6fada76721346b26a/oslo.privsep-2.2.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/55/76/a9d5657970658a884d452c98d7360a7e313fd218ccb6fada76721346b26a/oslo.privsep-2.2.1.tar.gz
Summary  : OpenStack library for privilege separation
Group    : Development/Tools
License  : Apache-2.0
Requires: oslo.privsep-bin = %{version}-%{release}
Requires: oslo.privsep-license = %{version}-%{release}
Requires: oslo.privsep-python = %{version}-%{release}
Requires: oslo.privsep-python3 = %{version}-%{release}
Requires: cffi
Requires: eventlet
Requires: greenlet
Requires: msgpack
Requires: oslo.config
Requires: oslo.i18n
Requires: oslo.log
Requires: oslo.utils
BuildRequires : buildreq-distutils3
BuildRequires : cffi
BuildRequires : eventlet
BuildRequires : greenlet
BuildRequires : hacking
BuildRequires : msgpack
BuildRequires : oslo.config
BuildRequires : oslo.i18n
BuildRequires : oslo.log
BuildRequires : oslo.utils
BuildRequires : pbr
BuildRequires : python-dateutil

%description
Team and repository tags
        ========================

%package bin
Summary: bin components for the oslo.privsep package.
Group: Binaries
Requires: oslo.privsep-license = %{version}-%{release}

%description bin
bin components for the oslo.privsep package.


%package license
Summary: license components for the oslo.privsep package.
Group: Default

%description license
license components for the oslo.privsep package.


%package python
Summary: python components for the oslo.privsep package.
Group: Default
Requires: oslo.privsep-python3 = %{version}-%{release}

%description python
python components for the oslo.privsep package.


%package python3
Summary: python3 components for the oslo.privsep package.
Group: Default
Requires: python3-core
Provides: pypi(oslo.privsep)
Requires: pypi(cffi)
Requires: pypi(eventlet)
Requires: pypi(greenlet)
Requires: pypi(msgpack)
Requires: pypi(oslo.config)
Requires: pypi(oslo.i18n)
Requires: pypi(oslo.log)
Requires: pypi(oslo.utils)

%description python3
python3 components for the oslo.privsep package.


%prep
%setup -q -n oslo.privsep-2.2.1
cd %{_builddir}/oslo.privsep-2.2.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1592852892
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/oslo.privsep
cp %{_builddir}/oslo.privsep-2.2.1/LICENSE %{buildroot}/usr/share/package-licenses/oslo.privsep/294b43b2cec9919063be1a3b49e8722648424779
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/privsep-helper

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/oslo.privsep/294b43b2cec9919063be1a3b49e8722648424779

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
